version: '3'
services:
  app:
    image: node:20
    container_name: node-docker-app
    working_dir: /usr/src/app
    networks:
      - mylocalnetwork
    volumes:
      - ./appsrc:/usr/src/app
    ports:
      - "3000:3000"
    command: >
      bash -c "tail -f /dev/null"
    depends_on:
      - mongodocker

  mongodocker:
    image: mongo
    container_name: mongodocker_container
    restart: always
    networks:
      - mylocalnetwork
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./data:/data/db

networks:
  mylocalnetwork:
    external: true
